### ISSUE TITLE
Need Exp date added

### ISSUE THREAD

**Issue by bardacres** [dboling19/inventory#10]
Need to add a field to enter the Expiration Date on the New Item screen (only going to enter the first date to expire).
Also, need to focus on the item box after the entry so that you do not have to go back to the mouse to refocus for the next entry.

**Comment by dboling19** [comment]
I could see this maybe being effective at first, but updating it later could be interesting when the oldest item leaves the system.  Without using an individual-item system, how would this work?  Currently, it is effectively setting the expiration date of the oldest item related to that listing.

Either that is good enough, or an overhaul of how items are stored and tracked is necessary.  

A possible overhaul could be just making a M-M table containing the item_id, loc_id, and expiration date.  Then the quantity will simply be the count of that item in the system, not directly connected.

**Comment by dboling19** [comment]
Addressed in PR #12
